const Images = {
  Background: {
    bg: require('../../assets/images/bg.png'),
    drawerBg: require('../../assets/images/drawerBg.png'),
  },
  Pictures: {

    appLogo: require('../../assets/images/logo.png'),
    loginLogo: require('../../assets/images/loginLogo.png'),
    left: require('../../assets/images/left.png'),
    mail: require('../../assets/images/mail.png'),
    drawerLogo: require('../../assets/images/drawerLogo.png'),
    homeHeaderText: require('../../assets/images/homeHeaderText.png'),
    notificationLogo: require('../../assets/images/notificationLogo.png'),
    profile1: require('../../assets/images/profile1.png'),
    headPhone: require('../../assets/images/headPhone.png'),
    greenShoes: require('../../assets/images/greenShoes.png'),
    tShirt1: require('../../assets/images/tShirt1.png'),
    purpleShoes: require('../../assets/images/purpleShoes.png'),
    tShirt2: require('../../assets/images/tShirt2.png'),
    airpods: require('../../assets/images/airPods.png'),
    nikeShoes: require('../../assets/images/nikeShoes.png'),
    nikeShoe1: require('../../assets/images/nikeshoe1.png'),
    blackHeadfone: require('../../assets/images/blackHeadfone.png'),
    tShirt: require('../../assets/images/t_shirt.png'),
    headfone: require('../../assets/images/headfone.png'),
    blackShoes: require('../../assets/images/blackShoes.png'),
    orangeShoes: require('../../assets/images/orangeShoes.png'),
    nikeshoe2: require('../../assets/images/nikeshoe2.png'),
    greenShoe1: require('../../assets/images/greenshoe1.png'),
    maskheader: require('../../assets/images/maskheader.png'),
    blackHeadphone: require('../../assets/images/blackHeadphones.png'),
    headericon1: require('../../assets/images/headericon1.png'),
    paypal: require('../../assets/images/paypal.png'),
    path70: require('../../assets/images/70.png'),
    Path69: require('../../assets/images/69.png'),


  },
  Icon: {
    logo: require('../../assets/images/logo.png'),
    star1: require('../../assets/images/star.png'),
    greenStar: require('../../assets/images/greenStar.png'),
    grayStar: require('../../assets/images/greyStar.png'),
    purpleStar: require('../../assets/images/purpleStar.png'),
    home: require('../../assets/images/homeIcon.png'),
    user: require('../../assets/images/userIcon.png'),
    // resubcription: require('../../assets/images/resubcriptionIcon.png'),
    favourite: require('../../assets/images/favouriteIcon.png'),
    card: require('../../assets/images/shoppingCardIcon.png'),
    contact: require('../../assets/images/contactIcon.png'),
    order: require('../../assets/images/myOrderIcon.png'),
    logout: require('../../assets/images/logOutIcon.png'),
    nextIcon: require('../../assets/images/next.png'),
    openCamera: require('../../assets/images/openCamera.png'),
    circle: require('../../assets/images/circle.png'),
  },
};

export { Images };
